### ISSUE TITLE
Next Image issue with Storybook/Tailwindcss

### ISSUE THREAD

**Issue by BkSouX** [theodorusclarence/expansion-pack#5]
Hi,

Im trying to use Nextjs with Storybook and Tailwindcss.
I have set this in the `preview.js`

```javascript
const OriginalNextImage = NextImage.default;
Object.defineProperty(NextImage, 'default', {
  configurable: true,
  value: (props) => <OriginalNextImage {...props} unoptimized />,
});
```

And in a component I have 
```html
<div className="flex-shrink-0 flex items-center">
             <Image
                    className="block lg:hidden h-8 w-auto"
                    src="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg"
                    width="50"
                    height="30"
                    alt="Workflow"
                  />
            <Image
                    className="hidden lg:block h-8 w-auto"
                    src="https://tailwindui.com/img/logos/workflow-logo-indigo-500-mark-white-text.svg"
                    width="128"
                    height="30"
                    alt="Workflow"
                  />
</div>
```

Images loads well but className are not working. Like Tailwind did not see them actually.. In my browser, I can't see config for "hidden" class for example.

Would you have an idea about that ? 
Have a good day

**Comment by BkSouX** [comment]
tailwind works if I set : 

```javascript
Object.defineProperty(NextImage, 'default', {
  configurable: true,
  value: (props) => <img {...props} />,
});
```

but I probably going to lose some stuff

Works also with

```javascript
Object.defineProperty(NextImage, "default", {
  configurable: true,
  value: (props) => <span className={props.className}><OriginalNextImage {...props} unoptimized /></span>,
});
```

**Comment by theodorusclarence** [comment]
Hey, that's more of Next.js Image thing rather than Storybook.

You can't use class to hide them, because Next.js use position absolute & inline style which adds `display: block` to the image. To hide image I usually use another wrapper for the Next Image

```tsx
<div className="hidden lg:block"> 
	  <Image
		    className="h-8 w-auto"
		    src="https://tailwindui.com/img/logos/workflow-logo-indigo-500-mark-white-text.svg"
		    width="128"
		    height="30"
		    alt="Workflow"
	  />
</div>
```

You can try opening a discussion on the Next.js repository if it doesn't work

<details>
<summary>Detail about inline style & absolute</summary>

![image](https://user-images.githubusercontent.com/55318172/159516538-e54e996e-af6d-450e-8b24-c5235440443b.png)


</details>
